#!/usr/bin/env python

"""taula2py - Translate a Taula code to Python code.

The Taula code needs to be restricted to Python constructs, so it can be easilly
translated.
"""

import sys
import os.path
from mmap import *
from struct import *


def t(level):
    """Indent line by level"""
    return "    " * level

def pairs(p):
    """Convert a list into a list of pairs."""
    return [(p[i], p[i+1]) for i in range(0, len(p), 2)]

def align64(length):
    return (length + 7) & 0xfffffffffffffff8

class YAHeader (object):
    def __init__(self, buf):
        kind, length, position = unpack("!4sLQ", buf)
        self.kind = kind
        self.length = length
        self.size = align64(length)

    def is_literal(self):
        return self.kind[0] == "#"

class YANode (object):
    def __init__(self, header):
        self.length = header.length
        self.size = header.size
        self.kind = header.kind
        self.childs = []

    def add(self, child):
        self.childs.append(child)

    # Write python code to a string.
    def wp(self, l = 0):
        if self.kind == "@pas":
            return None

        elif self.kind in ("modu", "bloc"):
            return "\n".join(child.wp(l) for child in self.childs) + "\n"

        elif self.kind == ".   ":
            return ".".join(child.wp() for child in self.childs)

        elif self.kind in (
            "<<  ", ">>  ", "*   ", "//  ", "/   ", "%   ", "+   ", "-   ", "&   ", "^   ",
            "|   ", "is  ", "==  ", "!=  ", "<   ", ">   ", "<=  ", ">=  ", "and ", "or  ", "in  ",
        ):
            op = " " + self.kind.strip() + " "
            return "(" + op.join(child.wp() for child in self.childs) + ")"

        elif self.kind == "=   ":
            return "\n" + t(l) + " = ".join(child.wp() for child in self.childs)

        elif self.kind == "fqnm":
            return ".".join(child.wp() for child in self.childs)

        elif self.kind == "fqns":
            return ", ".join(child.wp() for child in self.childs)

        elif self.kind == "farg":
            name, expr = [child.wp() for child in self.childs]
            return name if expr is None else "%s=%s" % (name, expr)

        elif self.kind == "carg":
            name, expr = [child.wp() for child in self.childs]
            return expr if name is None else "%s=%s" % (name, expr)

        elif self.kind == "func":
            name = self.childs[0].wp()
            block = self.childs[-1].wp(l + 1)
            arguments = ",".join(child.wp() for child in self.childs[1:-1])
            return t(l) + "\ndef %s(%s):\n%s" % (name, arguments, block)

        elif self.kind == "meth":
            name = self.childs[0].wp()
            block = self.childs[-1].wp(l + 1)
            arguments = ",".join(child.wp() for child in self.childs[1:-1])
            return t(l) + "\n" + t(l) + "def %s(this, %s):\n%s" % (name, arguments, block)

        elif self.kind == "clas":
            name = self.childs[0].wp()
            block = self.childs[-1].wp(l + 1)
            subclasses = self.childs[1].wp() if self.childs[1] is not None else "object"
            return t(l) + "\nclass %s(%s):\n%s" % (name, subclasses, block)

        elif self.kind == "x() ":
            name = self.childs[0].wp()
            arguments = ",".join(child.wp() for child in self.childs[1:])
            return t(l) + "%s(%s)" % (name, arguments)

        elif self.kind == "impo":
            name, _as = [child.wp() for child in self.childs]
            if _as is None:
                return "import %s" % (name,)
            else:
                return "import %s as %s" % (name, _as)

        else:
            raise NotImplementedError("Node '%s' unknown" % self.kind)

class YALiteral (YANode):
    def __init__(self, header, inner):
        YANode.__init__(self, header)

        if self.kind == "#id ":
            self.value = inner.decode("UTF-8")
        elif self.kind == "#str":
            self.value = repr(inner.decode("UTF-8"))
        elif self.kind[:2] in ("#i", "#u"):
            if self.kind == "#i64":
                (value,) = unpack("!q", inner)
            elif self.kind == "#u64":
                (value,) = unpack("!Q", inner)
            elif self.kind == "#i32":
                (value,) = unpack("!l", inner)
            elif self.kind == "#u32":
                (value,) = unpack("!L", inner)
            elif self.kind == "#i16":
                (value,) = unpack("!h", inner)
            elif self.kind == "#u16":
                (value,) = unpack("!H", inner)
            elif self.kind == "#i8":
                (value,) = unpack("!b", inner)
            elif self.kind == "#u8":
                (value,) = unpack("!B", inner)
            else:
                raise NotImplementedError("Literal type '%s' unknown" % (self.kind))
            self.value = repr(value)
        else:
            raise NotImplementedError("Literal type '%s' unknown" % (self.kind))

    def wp(self, l = 0):
        return self.value.encode("UTF-8")

def node_decode(buf):
    if len(buf) < 16:
        raise RuntimeError("!error: Not enough size to decode header.")

    header = YAHeader(buf[:16])
    inner = buf[16:header.length]
    inner_length = len(inner)

    if header.is_literal():
        node = YALiteral(header, inner)

    else:
        offset = 0
        node = YANode(header)
        while offset < inner_length:
            child = node_decode(inner[offset:])
            offset+= child.size
            node.add(child)

    return node

def main(argv):
    if len(argv) != 2:
        raise RuntimeError("Need one file argument")

    in_filename = argv[1]
    out_filename = os.path.splitext(in_filename)[0] + ".py"

    fdin = open(in_filename, "rb")
    buf = mmap(fdin.fileno(), 0, MAP_SHARED, PROT_READ)

    tree = node_decode(buf)

    buf.close()
    fdin.close()

    fdout = open(out_filename, "wb")
    fdout.write(tree.wp(0))


if __name__ == "__main__":
    exit(main(sys.argv))

